const questionsData = {
  general: {
    easy: [
      { question: "What color is the sky?", options: ["Blue", "Green", "Red", "Yellow"], correctIndex: 0 },
      { question: "How many days are in a week?", options: ["5", "6", "7", "8"], correctIndex: 2 },
      { question: "What is 2 + 2?", options: ["3", "4", "5", "6"], correctIndex: 1 },
      { question: "Which animal barks?", options: ["Cat", "Dog", "Cow", "Sheep"], correctIndex: 1 },
      { question: "What do bees make?", options: ["Milk", "Honey", "Water", "Oil"], correctIndex: 1 },
      { question: "Which planet is closest to the sun?", options: ["Venus", "Earth", "Mercury", "Mars"], correctIndex: 2 },
      { question: "What do you use to write?", options: ["Pen", "Phone", "Fork", "Spoon"], correctIndex: 0 },
      { question: "How many fingers do you have?", options: ["5", "10", "8", "6"], correctIndex: 1 },
      { question: "What color are bananas?", options: ["Red", "Yellow", "Blue", "Purple"], correctIndex: 1 },
      { question: "Which day comes after Monday?", options: ["Tuesday", "Friday", "Sunday", "Saturday"], correctIndex: 0 },
      { question: "How many continents are there?", options: ["5", "6", "7", "8"], correctIndex: 2 },
      { question: "What do plants need to grow?", options: ["Sunlight", "Chocolate", "Oil", "Salt"], correctIndex: 0 },
      { question: "Which month has 28 or 29 days?", options: ["January", "February", "March", "April"], correctIndex: 1 },
      { question: "What do we breathe in?", options: ["Oxygen", "Carbon dioxide", "Hydrogen", "Nitrogen"], correctIndex: 0 },
      { question: "Which fruit is typically red?", options: ["Banana", "Apple", "Orange", "Grapes"], correctIndex: 1 },
      { question: "How many legs does a cat have?", options: ["2", "3", "4", "5"], correctIndex: 2 },
      { question: "What color are grass?", options: ["Blue", "Green", "Yellow", "Red"], correctIndex: 1 },
      { question: "What do you call a baby dog?", options: ["Cub", "Puppy", "Calf", "Kitten"], correctIndex: 1 },
      { question: "Which animal is known as the king of the jungle?", options: ["Tiger", "Lion", "Elephant", "Giraffe"], correctIndex: 1 },
      { question: "What do we use to see?", options: ["Ears", "Nose", "Eyes", "Mouth"], correctIndex: 2 }
    ],
    medium: [
      { question: "What is the capital of France?", options: ["Berlin", "London", "Paris", "Madrid"], correctIndex: 2 },
      { question: "Which gas do plants absorb?", options: ["Oxygen", "Carbon Dioxide", "Nitrogen", "Helium"], correctIndex: 1 },
      { question: "How many states are in the USA?", options: ["50", "52", "48", "51"], correctIndex: 0 },
      { question: "What is H2O?", options: ["Water", "Oxygen", "Hydrogen", "Salt"], correctIndex: 0 },
      { question: "Which continent is Egypt in?", options: ["Asia", "Europe", "Africa", "Australia"], correctIndex: 2 },
      { question: "Which is the largest ocean?", options: ["Atlantic", "Pacific", "Indian", "Arctic"], correctIndex: 1 },
      { question: "How many legs does a spider have?", options: ["6", "8", "10", "4"], correctIndex: 1 },
      { question: "What is 12 * 12?", options: ["144", "124", "154", "134"], correctIndex: 0 },
      { question: "Who invented the telephone?", options: ["Edison", "Bell", "Tesla", "Newton"], correctIndex: 1 },
      { question: "What planet is known as the Red Planet?", options: ["Jupiter", "Mars", "Saturn", "Venus"], correctIndex: 1 },
      { question: "Which country is known for the Eiffel Tower?", options: ["Italy", "Spain", "France", "Germany"], correctIndex: 2 },
      { question: "Which instrument has keys, pedals, and strings?", options: ["Guitar", "Piano", "Violin", "Drums"], correctIndex: 1 },
      { question: "Which language is primarily spoken in Brazil?", options: ["Spanish", "Portuguese", "French", "English"], correctIndex: 1 },
      { question: "Who wrote 'Romeo and Juliet'?", options: ["Shakespeare", "Dickens", "Tolstoy", "Hemingway"], correctIndex: 0 },
      { question: "Which element is used in pencils?", options: ["Lead", "Iron", "Gold", "Carbon"], correctIndex: 3 },
      { question: "What is the hardest natural substance?", options: ["Diamond", "Gold", "Iron", "Silver"], correctIndex: 0 },
      { question: "Which country is famous for sushi?", options: ["China", "Japan", "Korea", "Thailand"], correctIndex: 1 },
      { question: "Which planet has the most moons?", options: ["Earth", "Mars", "Jupiter", "Saturn"], correctIndex: 2 },
      { question: "What currency is used in the UK?", options: ["Euro", "Dollar", "Pound Sterling", "Yen"], correctIndex: 2 },
      { question: "What does DNA stand for?", options: ["Deoxyribonucleic Acid", "Dinucleic Acid", "Dioxin Acid", "None"], correctIndex: 0 }
    ],
    hard: [
      { question: "What year did the Titanic sink?", options: ["1910", "1912", "1914", "1916"], correctIndex: 1 },
      { question: "What is the square root of 256?", options: ["12", "14", "16", "18"], correctIndex: 2 },
      { question: "Which element has the atomic number 1?", options: ["Oxygen", "Hydrogen", "Helium", "Carbon"], correctIndex: 1 },
      { question: "Who painted the Mona Lisa?", options: ["Van Gogh", "Picasso", "Da Vinci", "Rembrandt"], correctIndex: 2 },
      { question: "Which country has the largest population?", options: ["USA", "India", "China", "Russia"], correctIndex: 2 },
      { question: "What is the capital of Iceland?", options: ["Reykjavik", "Oslo", "Helsinki", "Stockholm"], correctIndex: 0 },
      { question: "Who discovered penicillin?", options: ["Fleming", "Curie", "Pasteur", "Newton"], correctIndex: 0 },
      { question: "What is the chemical symbol for gold?", options: ["Ag", "Au", "Gd", "Ga"], correctIndex: 1 },
      { question: "What is 17 squared?", options: ["289", "207", "278", "196"], correctIndex: 0 },
      { question: "Which language has the most native speakers?", options: ["English", "Spanish", "Mandarin", "Hindi"], correctIndex: 2 },
      { question: "In what year was the first man on the moon?", options: ["1967", "1968", "1969", "1970"], correctIndex: 2 },
      { question: "Who developed the theory of relativity?", options: ["Newton", "Einstein", "Tesla", "Bohr"], correctIndex: 1 },
      { question: "Which country hosted the 2016 Summer Olympics?", options: ["China", "UK", "Brazil", "Russia"], correctIndex: 2 },
      { question: "What is the longest river in the world?", options: ["Amazon", "Nile", "Yangtze", "Mississippi"], correctIndex: 1 },
      { question: "Who wrote 'The Odyssey'?", options: ["Homer", "Virgil", "Shakespeare", "Dante"], correctIndex: 0 },
      { question: "What is the capital of Mongolia?", options: ["Ulaanbaatar", "Astana", "Hanoi", "Jakarta"], correctIndex: 0 },
      { question: "Which country invented paper?", options: ["Egypt", "China", "Greece", "India"], correctIndex: 1 },
      { question: "What does CPU stand for in computers?", options: ["Central Processing Unit", "Central Power Unit", "Computer Processing Unit", "Central Performance Unit"], correctIndex: 0 },
      { question: "What year did World War II end?", options: ["1944", "1945", "1946", "1947"], correctIndex: 1 },
      { question: "What is Schrödinger's cat?", options: ["A thought experiment", "A real cat", "A novel", "A movie"], correctIndex: 0 }
    ]
  },

  science: {
    easy: [
      { question: "What is H2O?", options: ["Water", "Oxygen", "Hydrogen", "Salt"], correctIndex: 0 },
      { question: "What planet do we live on?", options: ["Mars", "Earth", "Venus", "Jupiter"], correctIndex: 1 },
      { question: "What gas do plants breathe in?", options: ["Oxygen", "Carbon Dioxide", "Nitrogen", "Helium"], correctIndex: 1 },
      { question: "Which organ pumps blood?", options: ["Liver", "Heart", "Kidneys", "Lungs"], correctIndex: 1 },
      { question: "What do bees produce?", options: ["Milk", "Honey", "Wax", "Sugar"], correctIndex: 1 },
      { question: "What is the boiling point of water?", options: ["100°C", "0°C", "50°C", "200°C"], correctIndex: 0 },
      { question: "What do we use to see?", options: ["Ears", "Eyes", "Nose", "Mouth"], correctIndex: 1 },
      { question: "Which animal lives in water?", options: ["Lion", "Whale", "Elephant", "Tiger"], correctIndex: 1 },
      { question: "What is the natural source of light during the day?", options: ["Moon", "Sun", "Stars", "Fire"], correctIndex: 1 },
      { question: "What is the freezing point of water?", options: ["0°C", "32°C", "100°C", "-10°C"], correctIndex: 0 },
      { question: "What gas do humans breathe out?", options: ["Oxygen", "Nitrogen", "Carbon Dioxide", "Hydrogen"], correctIndex: 2 },
      { question: "What part of a plant makes food?", options: ["Roots", "Stem", "Leaves", "Flowers"], correctIndex: 2 },
      { question: "What do plants need to grow?", options: ["Sunlight", "Chocolate", "Salt", "Plastic"], correctIndex: 0 },
      { question: "What is the largest planet in our solar system?", options: ["Earth", "Saturn", "Jupiter", "Mars"], correctIndex: 2 },
      { question: "Which sense helps you smell?", options: ["Sight", "Hearing", "Taste", "Smell"], correctIndex: 3 },
      { question: "What do you call a baby frog?", options: ["Cub", "Tadpole", "Puppy", "Calf"], correctIndex: 1 },
      { question: "What is the main gas in the air we breathe?", options: ["Oxygen", "Carbon Dioxide", "Nitrogen", "Hydrogen"], correctIndex: 2 },
      { question: "How many legs does an insect have?", options: ["4", "6", "8", "10"], correctIndex: 1 },
      { question: "Which organ is responsible for breathing?", options: ["Heart", "Lungs", "Brain", "Stomach"], correctIndex: 1 },
      { question: "What do humans need to live?", options: ["Water", "Air", "Food", "All of the above"], correctIndex: 3 }
    ],
    medium: [
      { question: "What is the chemical symbol for oxygen?", options: ["O", "Ox", "Oy", "Om"], correctIndex: 0 },
      { question: "Which organelle is known as the powerhouse of the cell?", options: ["Nucleus", "Mitochondria", "Ribosome", "Chloroplast"], correctIndex: 1 },
      { question: "What force keeps us on the ground?", options: ["Magnetism", "Gravity", "Friction", "Electricity"], correctIndex: 1 },
      { question: "What type of blood cells help fight infection?", options: ["Red", "White", "Platelets", "Plasma"], correctIndex: 1 },
      { question: "What is the chemical formula for table salt?", options: ["NaCl", "KCl", "NaOH", "CaCl2"], correctIndex: 0 },
      { question: "Which planet is known as the Red Planet?", options: ["Mars", "Jupiter", "Saturn", "Venus"], correctIndex: 0 },
      { question: "What is photosynthesis?", options: ["Process by which plants make food", "Animal breathing", "Rock formation", "Water cycle"], correctIndex: 0 },
      { question: "What is the human body's largest organ?", options: ["Liver", "Skin", "Heart", "Brain"], correctIndex: 1 },
      { question: "What is the pH level of pure water?", options: ["7", "0", "14", "1"], correctIndex: 0 },
      { question: "Which gas is most abundant in Earth's atmosphere?", options: ["Oxygen", "Carbon Dioxide", "Nitrogen", "Hydrogen"], correctIndex: 2 },
      { question: "What type of energy comes from the sun?", options: ["Kinetic", "Thermal", "Solar", "Electrical"], correctIndex: 2 },
      { question: "What kind of animal is a Komodo dragon?", options: ["Mammal", "Reptile", "Bird", "Fish"], correctIndex: 1 },
      { question: "Which organ filters blood in the human body?", options: ["Liver", "Kidneys", "Heart", "Lungs"], correctIndex: 1 },
      { question: "What part of the eye controls the amount of light?", options: ["Lens", "Retina", "Pupil", "Cornea"], correctIndex: 2 },
      { question: "Which gas is necessary for combustion?", options: ["Oxygen", "Nitrogen", "Carbon Dioxide", "Helium"], correctIndex: 0 },
      { question: "What is the main function of red blood cells?", options: ["Fight infection", "Carry oxygen", "Clot blood", "Produce hormones"], correctIndex: 1 },
      { question: "Which vitamin is produced when skin is exposed to sunlight?", options: ["Vitamin A", "Vitamin B", "Vitamin C", "Vitamin D"], correctIndex: 3 },
      { question: "What do antibiotics treat?", options: ["Viruses", "Bacteria", "Fungi", "All of the above"], correctIndex: 1 },
      { question: "What particle has a positive charge?", options: ["Electron", "Proton", "Neutron", "Photon"], correctIndex: 1 },
      { question: "Which type of rock is formed from cooled lava?", options: ["Sedimentary", "Igneous", "Metamorphic", "Fossil"], correctIndex: 1 }
    ],
    hard: [
      { question: "What is the name of the process where cells divide?", options: ["Mitosis", "Meiosis", "Osmosis", "Photosynthesis"], correctIndex: 0 },
      { question: "Who developed the theory of evolution by natural selection?", options: ["Darwin", "Newton", "Einstein", "Galileo"], correctIndex: 0 },
      { question: "What is the powerhouse of the cell?", options: ["Nucleus", "Mitochondria", "Ribosome", "Golgi apparatus"], correctIndex: 1 },
      { question: "What is the second most abundant gas in the Earth's atmosphere?", options: ["Oxygen", "Argon", "Nitrogen", "Carbon Dioxide"], correctIndex: 0 },
      { question: "What kind of bond involves the sharing of electron pairs?", options: ["Ionic", "Covalent", "Metallic", "Hydrogen"], correctIndex: 1 },
      { question: "Which vitamin is important for blood clotting?", options: ["Vitamin A", "Vitamin K", "Vitamin C", "Vitamin D"], correctIndex: 1 },
      { question: "What is the atomic number of carbon?", options: ["6", "12", "14", "8"], correctIndex: 0 },
      { question: "What does DNA stand for?", options: ["Deoxyribonucleic Acid", "Dinucleic Acid", "Deoxyribose Acid", "Dioxin Acid"], correctIndex: 0 },
      { question: "Which planet has the shortest day?", options: ["Jupiter", "Mars", "Earth", "Venus"], correctIndex: 0 },
      { question: "What is the process of water vapor turning into liquid?", options: ["Condensation", "Evaporation", "Precipitation", "Sublimation"], correctIndex: 0 },
      { question: "Which scientist is known for the laws of motion?", options: ["Einstein", "Newton", "Galileo", "Tesla"], correctIndex: 1 },
      { question: "Which element is liquid at room temperature?", options: ["Mercury", "Gold", "Iron", "Silver"], correctIndex: 0 },
      { question: "What is the main gas responsible for the greenhouse effect?", options: ["Oxygen", "Carbon Dioxide", "Nitrogen", "Methane"], correctIndex: 1 },
      { question: "What part of the brain controls balance?", options: ["Cerebrum", "Cerebellum", "Brainstem", "Hypothalamus"], correctIndex: 1 },
      { question: "What is the term for animals that eat both plants and meat?", options: ["Herbivores", "Carnivores", "Omnivores", "Detritivores"], correctIndex: 2 },
      { question: "What is the hardest naturally occurring mineral?", options: ["Quartz", "Diamond", "Topaz", "Corundum"], correctIndex: 1 },
      { question: "Which organ produces insulin?", options: ["Liver", "Pancreas", "Kidneys", "Stomach"], correctIndex: 1 },
      { question: "What is the name of the process by which green plants make their food?", options: ["Photosynthesis", "Respiration", "Fermentation", "Transpiration"], correctIndex: 0 },
      { question: "Which particle has no electric charge?", options: ["Proton", "Electron", "Neutron", "Photon"], correctIndex: 2 },
      { question: "What is the term for a solution with a pH less than 7?", options: ["Neutral", "Acidic", "Basic", "Alkaline"], correctIndex: 1 }
    ]
  },
  
  math: {
    easy: [
      { question: "What is 2 + 2?", options: ["3", "4", "5", "6"], correctIndex: 1 },
      { question: "What is 5 - 3?", options: ["1", "2", "3", "4"], correctIndex: 1 },
      { question: "What is 10 ÷ 2?", options: ["2", "3", "4", "5"], correctIndex: 3 },
      { question: "What is 3 × 3?", options: ["6", "7", "8", "9"], correctIndex: 3 },
      { question: "What is the next number after 9?", options: ["7", "8", "10", "11"], correctIndex: 2 },
      { question: "How many sides does a triangle have?", options: ["2", "3", "4", "5"], correctIndex: 1 },
      { question: "What is half of 8?", options: ["2", "3", "4", "5"], correctIndex: 2 },
      { question: "What is 7 + 1?", options: ["6", "7", "8", "9"], correctIndex: 2 },
      { question: "Which is the smallest number?", options: ["1", "0", "2", "3"], correctIndex: 1 },
      { question: "What is 6 - 4?", options: ["1", "2", "3", "4"], correctIndex: 1 },
      { question: "What shape has four equal sides?", options: ["Rectangle", "Square", "Triangle", "Circle"], correctIndex: 1 },
      { question: "What is 9 + 0?", options: ["9", "10", "11", "12"], correctIndex: 0 },
      { question: "What is 8 - 5?", options: ["2", "3", "4", "5"], correctIndex: 1 },
      { question: "How many fingers do you have?", options: ["8", "9", "10", "11"], correctIndex: 2 },
      { question: "What is 4 × 2?", options: ["6", "7", "8", "9"], correctIndex: 2 },
      { question: "What is the sum of 1 and 6?", options: ["6", "7", "8", "9"], correctIndex: 1 },
      { question: "What is 10 minus 7?", options: ["2", "3", "4", "5"], correctIndex: 1 },
      { question: "Which number comes before 5?", options: ["4", "6", "7", "3"], correctIndex: 0 },
      { question: "What is double of 3?", options: ["4", "5", "6", "7"], correctIndex: 2 },
      { question: "How many hours are there in a day?", options: ["24", "12", "48", "36"], correctIndex: 0 }
    ],
    medium: [
      { question: "What is 12 × 12?", options: ["124", "142", "144", "134"], correctIndex: 2 },
      { question: "What is 100 ÷ 4?", options: ["20", "25", "30", "24"], correctIndex: 1 },
      { question: "What is the square root of 81?", options: ["7", "8", "9", "10"], correctIndex: 2 },
      { question: "What is 15 + 27?", options: ["41", "42", "43", "44"], correctIndex: 2 },
      { question: "What is 50% of 200?", options: ["100", "150", "50", "200"], correctIndex: 0 },
      { question: "What is the perimeter of a square with side 5?", options: ["10", "15", "20", "25"], correctIndex: 2 },
      { question: "What is the value of pi (approx)?", options: ["2.14", "3.14", "4.14", "3.41"], correctIndex: 1 },
      { question: "What is 7²?", options: ["49", "47", "50", "48"], correctIndex: 0 },
      { question: "What is 0.5 as a fraction?", options: ["1/2", "1/3", "1/4", "1/5"], correctIndex: 0 },
      { question: "What is the area of a rectangle with length 4 and width 3?", options: ["7", "10", "12", "15"], correctIndex: 2 },
      { question: "What is 2³?", options: ["6", "8", "9", "7"], correctIndex: 1 },
      { question: "What is 45 ÷ 9?", options: ["4", "5", "6", "7"], correctIndex: 1 },
      { question: "What is 9 × 6?", options: ["54", "56", "52", "48"], correctIndex: 0 },
      { question: "Which is a prime number?", options: ["21", "22", "23", "24"], correctIndex: 2 },
      { question: "What is the cube root of 27?", options: ["3", "9", "6", "27"], correctIndex: 0 },
      { question: "What is 3/4 as a decimal?", options: ["0.25", "0.5", "0.75", "1"], correctIndex: 2 },
      { question: "What is the next number in the sequence: 2, 4, 8, 16, ?", options: ["18", "20", "32", "24"], correctIndex: 2 },
      { question: "What is 5 × 5 × 5?", options: ["100", "125", "150", "115"], correctIndex: 1 },
      { question: "What is 11 × 11?", options: ["111", "121", "112", "131"], correctIndex: 1 },
      { question: "What is 81 ÷ 9?", options: ["8", "9", "7", "6"], correctIndex: 1 }
    ],
    hard: [
      { question: "What is the derivative of x²?", options: ["x", "2x", "x²", "2"], correctIndex: 1 },
      { question: "What is the integral of 2x dx?", options: ["x² + C", "2x + C", "x + C", "2 + C"], correctIndex: 0 },
      { question: "What is the value of sin 90°?", options: ["0", "0.5", "1", "-1"], correctIndex: 2 },
      { question: "What is the solution to the equation 3x - 9 = 0?", options: ["0", "1", "2", "3"], correctIndex: 3 },
      { question: "What is the sum of the interior angles of a hexagon?", options: ["720°", "540°", "360°", "480°"], correctIndex: 1 },
      { question: "What is the factorial of 5 (5!)?", options: ["120", "60", "20", "100"], correctIndex: 0 },
      { question: "What is the next prime number after 31?", options: ["33", "35", "37", "39"], correctIndex: 2 },
      { question: "What is the value of log₁₀ 1000?", options: ["1", "2", "3", "4"], correctIndex: 2 },
      { question: "What is the quadratic formula?", options: ["x = (-b ± √(b²-4ac))/2a", "x = (b ± √(b²-4ac))/2a", "x = (-b ± √(4ac-b²))/2a", "x = (b ± √(4ac-b²))/2a"], correctIndex: 0 },
      { question: "What is the sum of an arithmetic series 1 + 3 + 5 + ... + 19?", options: ["90", "100", "110", "95"], correctIndex: 0 },
      { question: "What is the complex number i squared?", options: ["1", "-1", "0", "i"], correctIndex: 1 },
      { question: "What is the slope of the line y = 3x + 7?", options: ["3", "7", "-3", "0"], correctIndex: 0 },
      { question: "If f(x) = x², what is f'(3)?", options: ["3", "6", "9", "12"], correctIndex: 1 },
      { question: "What is the sum of angles in a triangle?", options: ["180°", "90°", "360°", "270°"], correctIndex: 0 },
      { question: "What is the length of the hypotenuse of a right triangle with legs 3 and 4?", options: ["5", "6", "7", "8"], correctIndex: 0 },
      { question: "What is the binomial coefficient '5 choose 2'?", options: ["10", "15", "20", "25"], correctIndex: 0 },
      { question: "What is the formula for the area of a circle?", options: ["πr²", "2πr", "πd", "πr"], correctIndex: 0 },
      { question: "What is the next number in the Fibonacci sequence after 21?", options: ["32", "33", "34", "55"], correctIndex: 3 },
      { question: "What is the equation of a circle with center (0,0) and radius r?", options: ["x² + y² = r²", "x + y = r", "x² - y² = r²", "x² + y = r"], correctIndex: 0 },
      { question: "What is the probability of flipping a coin and getting heads?", options: ["0.25", "0.5", "0.75", "1"], correctIndex: 1 }
    ]
  },
    sports: {
    easy: [
      { question: "How many players are on a soccer team on the field?", options: ["9", "10", "11", "12"], correctIndex: 2 },
      { question: "Which sport is known as 'the king of sports'?", options: ["Basketball", "Soccer", "Baseball", "Tennis"], correctIndex: 1 },
      { question: "In which sport do you use a racket to hit a shuttlecock?", options: ["Tennis", "Badminton", "Squash", "Table Tennis"], correctIndex: 1 },
      { question: "How many points is a touchdown worth in American football?", options: ["3", "6", "7", "1"], correctIndex: 1 },
      { question: "Which sport uses a puck?", options: ["Soccer", "Hockey", "Basketball", "Volleyball"], correctIndex: 1 },
      { question: "How many bases are on a baseball field?", options: ["2", "3", "4", "5"], correctIndex: 2 },
      { question: "What color card is shown for a foul in soccer?", options: ["Red", "Green", "Yellow", "Blue"], correctIndex: 2 },
      { question: "Which sport is played on a court with a net and a ball?", options: ["Soccer", "Volleyball", "Golf", "Swimming"], correctIndex: 1 },
      { question: "Which sport involves a bow and arrow?", options: ["Archery", "Fencing", "Shooting", "Golf"], correctIndex: 0 },
      { question: "Which sport is known as the 'fastest game on ice'?", options: ["Hockey", "Curling", "Skating", "Luge"], correctIndex: 0 }
    ],
    medium: [
      { question: "How long is an Olympic swimming pool?", options: ["25 meters", "50 meters", "100 meters", "200 meters"], correctIndex: 1 },
      { question: "Which country won the FIFA World Cup in 2018?", options: ["Brazil", "Germany", "France", "Argentina"], correctIndex: 2 },
      { question: "What is the maximum score in a single frame of bowling?", options: ["10", "20", "30", "40"], correctIndex: 2 },
      { question: "In tennis, what follows 'deuce' in scoring?", options: ["Advantage", "Game", "Set", "Match"], correctIndex: 0 },
      { question: "Which NFL team has won the most Super Bowls?", options: ["Dallas Cowboys", "New England Patriots", "Pittsburgh Steelers", "San Francisco 49ers"], correctIndex: 1 },
      { question: "Which sport uses the terms 'spike' and 'block'?", options: ["Basketball", "Volleyball", "Handball", "Rugby"], correctIndex: 1 },
      { question: "In which sport can you score a 'hat-trick'?", options: ["Cricket", "Soccer", "Hockey", "All of the above"], correctIndex: 3 },
      { question: "How many players are there in a rugby union team?", options: ["11", "13", "15", "18"], correctIndex: 2 },
      { question: "What color is the ball in professional snooker?", options: ["Red", "White", "Black", "Green"], correctIndex: 0 },
      { question: "What is the distance of a marathon race?", options: ["21.1 km", "42.195 km", "50 km", "100 km"], correctIndex: 1 }
    ],
    hard: [
      { question: "Who holds the record for the most home runs in MLB history?", options: ["Babe Ruth", "Barry Bonds", "Hank Aaron", "Alex Rodriguez"], correctIndex: 1 },
      { question: "What year were the first modern Olympic Games held?", options: ["1896", "1900", "1912", "1924"], correctIndex: 0 },
      { question: "In Formula 1, how many points does the winner of a race earn?", options: ["10", "25", "30", "50"], correctIndex: 1 },
      { question: "Which country invented the sport of volleyball?", options: ["USA", "Canada", "England", "Australia"], correctIndex: 0 },
      { question: "In cricket, how many runs is a 'six' worth?", options: ["4", "5", "6", "7"], correctIndex: 2 },
      { question: "Which tennis player has the most Grand Slam singles titles?", options: ["Roger Federer", "Rafael Nadal", "Novak Djokovic", "Serena Williams"], correctIndex: 2 },
      { question: "What is the diameter of a basketball hoop in inches?", options: ["16", "18", "20", "22"], correctIndex: 1 },
      { question: "Who is known as 'The Greatest' in boxing?", options: ["Mike Tyson", "Muhammad Ali", "Joe Frazier", "George Foreman"], correctIndex: 1 },
      { question: "Which country won the first FIFA World Cup?", options: ["Brazil", "Uruguay", "Argentina", "Italy"], correctIndex: 1 },
      { question: "In golf, what is the term for a score of three under par on a single hole?", options: ["Birdie", "Eagle", "Albatross", "Bogey"], correctIndex: 2 }
    ]
  },
  history: {
    easy: [
      { question: "Who was the first President of the United States?", options: ["George Washington", "Abraham Lincoln", "Thomas Jefferson", "John Adams"], correctIndex: 0 },
      { question: "Which country built the Great Wall?", options: ["China", "Egypt", "India", "Greece"], correctIndex: 0 },
      { question: "What year did World War I start?", options: ["1912", "1914", "1916", "1918"], correctIndex: 1 },
      { question: "Who discovered America?", options: ["Christopher Columbus", "Leif Erikson", "Vasco da Gama", "Ferdinand Magellan"], correctIndex: 0 },
      { question: "Which city was the capital of the Roman Empire?", options: ["Athens", "Rome", "Carthage", "Constantinople"], correctIndex: 1 },
      { question: "Who was known as the Maid of Orléans?", options: ["Joan of Arc", "Cleopatra", "Marie Curie", "Queen Victoria"], correctIndex: 0 },
      { question: "Which war was fought between the North and South in the USA?", options: ["Revolutionary War", "Civil War", "World War I", "Vietnam War"], correctIndex: 1 },
      { question: "Who invented the printing press?", options: ["Gutenberg", "Tesla", "Newton", "Edison"], correctIndex: 0 },
      { question: "What ancient civilization built the pyramids?", options: ["Romans", "Egyptians", "Greeks", "Mayans"], correctIndex: 1 },
      { question: "When was the Declaration of Independence signed?", options: ["1776", "1783", "1800", "1750"], correctIndex: 0 }
    ],
    medium: [
      { question: "Who was the British Prime Minister during World War II?", options: ["Winston Churchill", "Neville Chamberlain", "Clement Attlee", "Margaret Thatcher"], correctIndex: 0 },
      { question: "What empire was ruled by Genghis Khan?", options: ["Mongol Empire", "Ottoman Empire", "Roman Empire", "Persian Empire"], correctIndex: 0 },
      { question: "What was the name of the ship on which the Pilgrims traveled to America?", options: ["Mayflower", "Santa Maria", "Beagle", "Endeavour"], correctIndex: 0 },
      { question: "Which revolution began in 1789?", options: ["American Revolution", "French Revolution", "Russian Revolution", "Industrial Revolution"], correctIndex: 1 },
      { question: "Who was the first woman to fly solo across the Atlantic?", options: ["Amelia Earhart", "Harriet Quimby", "Bessie Coleman", "Sally Ride"], correctIndex: 0 },
      { question: "What treaty ended World War I?", options: ["Treaty of Versailles", "Treaty of Paris", "Treaty of Ghent", "Treaty of Tordesillas"], correctIndex: 0 },
      { question: "Which U.S. President was assassinated in 1963?", options: ["John F. Kennedy", "Abraham Lincoln", "James Garfield", "William McKinley"], correctIndex: 0 },
      { question: "What was the name of the first successful English colony in America?", options: ["Jamestown", "Plymouth", "Roanoke", "Salem"], correctIndex: 0 },
      { question: "Who was the longest reigning British monarch before Queen Elizabeth II?", options: ["Queen Victoria", "King George III", "Queen Anne", "King Henry VIII"], correctIndex: 0 },
      { question: "Which war was fought from 1939 to 1945?", options: ["World War I", "World War II", "Cold War", "Vietnam War"], correctIndex: 1 }
    ],
    hard: [
      { question: "What year did the Berlin Wall fall?", options: ["1987", "1989", "1991", "1993"], correctIndex: 1 },
      { question: "Who was the first Emperor of Rome?", options: ["Julius Caesar", "Augustus", "Nero", "Caligula"], correctIndex: 1 },
      { question: "Which treaty ended the Thirty Years' War in 1648?", options: ["Treaty of Westphalia", "Treaty of Utrecht", "Treaty of Paris", "Treaty of Versailles"], correctIndex: 0 },
      { question: "What year did the Russian Revolution take place?", options: ["1917", "1905", "1922", "1939"], correctIndex: 0 },
      { question: "Who wrote the 'Communist Manifesto'?", options: ["Karl Marx", "Friedrich Engels", "Vladimir Lenin", "Joseph Stalin"], correctIndex: 0 },
      { question: "Where was the first Olympic Games held?", options: ["Athens", "Rome", "Sparta", "Delphi"], correctIndex: 0 },
      { question: "What empire was ruled by Suleiman the Magnificent?", options: ["Ottoman Empire", "Roman Empire", "Mongol Empire", "Persian Empire"], correctIndex: 0 },
      { question: "Which event started on October 29, 1929?", options: ["The Great Depression", "World War I", "The Cold War", "The Dust Bowl"], correctIndex: 0 },
      { question: "Who was the last Tsar of Russia?", options: ["Nicholas II", "Alexander III", "Peter the Great", "Ivan the Terrible"], correctIndex: 0 },
      { question: "What was the significance of the Magna Carta?", options: ["Limited the power of the king", "Started the Renaissance", "Ended the Hundred Years' War", "Founded the British Parliament"], correctIndex: 0 }
    ]
  },
  history: {
    easy: [
      { question: "Who was the first President of the United States?", options: ["George Washington", "Abraham Lincoln", "Thomas Jefferson", "John Adams"], correctIndex: 0 },
      { question: "Which country built the Great Wall?", options: ["China", "Egypt", "India", "Greece"], correctIndex: 0 },
      { question: "What year did World War I start?", options: ["1912", "1914", "1916", "1918"], correctIndex: 1 },
      { question: "Who discovered America?", options: ["Christopher Columbus", "Leif Erikson", "Vasco da Gama", "Ferdinand Magellan"], correctIndex: 0 },
      { question: "Which city was the capital of the Roman Empire?", options: ["Athens", "Rome", "Carthage", "Constantinople"], correctIndex: 1 },
      { question: "Who was known as the Maid of Orléans?", options: ["Joan of Arc", "Cleopatra", "Marie Curie", "Queen Victoria"], correctIndex: 0 },
      { question: "Which war was fought between the North and South in the USA?", options: ["Revolutionary War", "Civil War", "World War I", "Vietnam War"], correctIndex: 1 },
      { question: "Who invented the printing press?", options: ["Gutenberg", "Tesla", "Newton", "Edison"], correctIndex: 0 },
      { question: "What ancient civilization built the pyramids?", options: ["Romans", "Egyptians", "Greeks", "Mayans"], correctIndex: 1 },
      { question: "When was the Declaration of Independence signed?", options: ["1776", "1783", "1800", "1750"], correctIndex: 0 }
    ],
    medium: [
      { question: "Who was the British Prime Minister during World War II?", options: ["Winston Churchill", "Neville Chamberlain", "Clement Attlee", "Margaret Thatcher"], correctIndex: 0 },
      { question: "What empire was ruled by Genghis Khan?", options: ["Mongol Empire", "Ottoman Empire", "Roman Empire", "Persian Empire"], correctIndex: 0 },
      { question: "What was the name of the ship on which the Pilgrims traveled to America?", options: ["Mayflower", "Santa Maria", "Beagle", "Endeavour"], correctIndex: 0 },
      { question: "Which revolution began in 1789?", options: ["American Revolution", "French Revolution", "Russian Revolution", "Industrial Revolution"], correctIndex: 1 },
      { question: "Who was the first woman to fly solo across the Atlantic?", options: ["Amelia Earhart", "Harriet Quimby", "Bessie Coleman", "Sally Ride"], correctIndex: 0 },
      { question: "What treaty ended World War I?", options: ["Treaty of Versailles", "Treaty of Paris", "Treaty of Ghent", "Treaty of Tordesillas"], correctIndex: 0 },
      { question: "Which U.S. President was assassinated in 1963?", options: ["John F. Kennedy", "Abraham Lincoln", "James Garfield", "William McKinley"], correctIndex: 0 },
      { question: "What was the name of the first successful English colony in America?", options: ["Jamestown", "Plymouth", "Roanoke", "Salem"], correctIndex: 0 },
      { question: "Who was the longest reigning British monarch before Queen Elizabeth II?", options: ["Queen Victoria", "King George III", "Queen Anne", "King Henry VIII"], correctIndex: 0 },
      { question: "Which war was fought from 1939 to 1945?", options: ["World War I", "World War II", "Cold War", "Vietnam War"], correctIndex: 1 }
    ],
    hard: [
      { question: "What year did the Berlin Wall fall?", options: ["1987", "1989", "1991", "1993"], correctIndex: 1 },
      { question: "Who was the first Emperor of Rome?", options: ["Julius Caesar", "Augustus", "Nero", "Caligula"], correctIndex: 1 },
      { question: "Which treaty ended the Thirty Years' War in 1648?", options: ["Treaty of Westphalia", "Treaty of Utrecht", "Treaty of Paris", "Treaty of Versailles"], correctIndex: 0 },
      { question: "What year did the Russian Revolution take place?", options: ["1917", "1905", "1922", "1939"], correctIndex: 0 },
      { question: "Who wrote the 'Communist Manifesto'?", options: ["Karl Marx", "Friedrich Engels", "Vladimir Lenin", "Joseph Stalin"], correctIndex: 0 },
      { question: "Where was the first Olympic Games held?", options: ["Athens", "Rome", "Sparta", "Delphi"], correctIndex: 0 },
      { question: "What empire was ruled by Suleiman the Magnificent?", options: ["Ottoman Empire", "Roman Empire", "Mongol Empire", "Persian Empire"], correctIndex: 0 },
      { question: "Which event started on October 29, 1929?", options: ["The Great Depression", "World War I", "The Cold War", "The Dust Bowl"], correctIndex: 0 },
      { question: "Who was the last Tsar of Russia?", options: ["Nicholas II", "Alexander III", "Peter the Great", "Ivan the Terrible"], correctIndex: 0 },
      { question: "What was the significance of the Magna Carta?", options: ["Limited the power of the king", "Started the Renaissance", "Ended the Hundred Years' War", "Founded the British Parliament"], correctIndex: 0 }
    ]
  },
  literature: {
    easy: [
      { question: "Who wrote 'Romeo and Juliet'?", options: ["William Shakespeare", "Charles Dickens", "Mark Twain", "Jane Austen"], correctIndex: 0 },
      { question: "What is the name of the wizarding school in 'Harry Potter'?", options: ["Hogwarts", "Beauxbatons", "Durmstrang", "Ilvermorny"], correctIndex: 0 },
      { question: "Who is the author of 'The Cat in the Hat'?", options: ["Dr. Seuss", "Roald Dahl", "J.K. Rowling", "C.S. Lewis"], correctIndex: 0 },
      { question: "Which novel features the character Atticus Finch?", options: ["To Kill a Mockingbird", "The Great Gatsby", "1984", "Moby Dick"], correctIndex: 0 },
      { question: "In which book would you find a character named Tom Sawyer?", options: ["The Adventures of Tom Sawyer", "Oliver Twist", "Huckleberry Finn", "Treasure Island"], correctIndex: 0 },
      { question: "Who wrote 'Pride and Prejudice'?", options: ["Jane Austen", "Charlotte Brontë", "Emily Dickinson", "Virginia Woolf"], correctIndex: 0 },
      { question: "Which Shakespeare play features the character Macbeth?", options: ["Macbeth", "Hamlet", "Othello", "King Lear"], correctIndex: 0 },
      { question: "Who is the author of 'Charlie and the Chocolate Factory'?", options: ["Roald Dahl", "J.K. Rowling", "Dr. Seuss", "C.S. Lewis"], correctIndex: 0 },
      { question: "What type of creature is Smaug in 'The Hobbit'?", options: ["Dragon", "Troll", "Goblin", "Elf"], correctIndex: 0 },
      { question: "Who wrote 'The Odyssey'?", options: ["Homer", "Virgil", "Dante", "Sophocles"], correctIndex: 0 }
    ],
    medium: [
      { question: "Which novel begins with the line, 'Call me Ishmael'?", options: ["Moby Dick", "Great Expectations", "The Catcher in the Rye", "Lord of the Flies"], correctIndex: 0 },
      { question: "Who wrote 'One Hundred Years of Solitude'?", options: ["Gabriel García Márquez", "Pablo Neruda", "Jorge Luis Borges", "Isabel Allende"], correctIndex: 0 },
      { question: "In which novel is the character Jay Gatsby found?", options: ["The Great Gatsby", "East of Eden", "The Sun Also Rises", "The Grapes of Wrath"], correctIndex: 0 },
      { question: "Which English poet wrote 'Paradise Lost'?", options: ["John Milton", "William Blake", "Geoffrey Chaucer", "Alexander Pope"], correctIndex: 0 },
      { question: "What is the name of Sherlock Holmes’ assistant?", options: ["Dr. John Watson", "Inspector Lestrade", "Mycroft Holmes", "Professor Moriarty"], correctIndex: 0 },
      { question: "Who wrote the play 'Waiting for Godot'?", options: ["Samuel Beckett", "Arthur Miller", "Tennessee Williams", "Eugene O'Neill"], correctIndex: 0 },
      { question: "Which novel features the dystopian world of Oceania?", options: ["1984", "Brave New World", "Fahrenheit 451", "The Handmaid’s Tale"], correctIndex: 0 },
      { question: "Who wrote 'The Picture of Dorian Gray'?", options: ["Oscar Wilde", "Bram Stoker", "Mary Shelley", "Robert Louis Stevenson"], correctIndex: 0 },
      { question: "What is the pen name of the Brontë sisters?", options: ["Currer, Ellis, and Acton Bell", "George Eliot", "Lewis Carroll", "Mark Twain"], correctIndex: 0 },
      { question: "Which Shakespeare play is set on the Scottish heath?", options: ["Macbeth", "Hamlet", "Othello", "Julius Caesar"], correctIndex: 0 }
    ],
    hard: [
      { question: "Who wrote 'The Waste Land'?", options: ["T.S. Eliot", "Ezra Pound", "W.B. Yeats", "Robert Frost"], correctIndex: 0 },
      { question: "In which novel does the character Offred appear?", options: ["The Handmaid's Tale", "The Bell Jar", "Beloved", "The Road"], correctIndex: 0 },
      { question: "Who is the author of 'Don Quixote'?", options: ["Miguel de Cervantes", "Lope de Vega", "Federico García Lorca", "Jorge Luis Borges"], correctIndex: 0 },
      { question: "Which epic poem was written by Virgil?", options: ["The Aeneid", "The Iliad", "The Odyssey", "Beowulf"], correctIndex: 0 },
      { question: "What is the narrative style of James Joyce’s 'Ulysses'?", options: ["Stream of consciousness", "Epistolary", "Third-person omniscient", "First-person"], correctIndex: 0 },
      { question: "Who wrote 'The Divine Comedy'?", options: ["Dante Alighieri", "Geoffrey Chaucer", "John Milton", "Homer"], correctIndex: 0 },
      { question: "Which novel is narrated by the character Nick Carraway?", options: ["The Great Gatsby", "Tender Is the Night", "The Sun Also Rises", "East of Eden"], correctIndex: 0 },
      { question: "Who wrote the play 'A Streetcar Named Desire'?", options: ["Tennessee Williams", "Arthur Miller", "Samuel Beckett", "Lorraine Hansberry"], correctIndex: 0 },
      { question: "Which author created the character Raskolnikov?", options: ["Fyodor Dostoevsky", "Leo Tolstoy", "Anton Chekhov", "Ivan Turgenev"], correctIndex: 0 },
      { question: "Which novel deals with the theme of the American Dream and was written by John Steinbeck?", options: ["The Grapes of Wrath", "Of Mice and Men", "East of Eden", "The Red Pony"], correctIndex: 0 }
    ]
  }
};



